### ISSUE TITLE
Add Search Functionality to Disc Server

### ISSUE THREAD

**Issue by jreyes4** [PhilipBeckwith/Discord-Bots#10]
# Proposed Change
Looking to add a bot command keyword to the steambot module that allows us to search the games database and return a list of users that own that game. 

# Reason for Change
Currently there is no way for members to search on specific games of interest. This command will allow them to focus their searches. 

# Proposed Implementation Notes
- The command will likely be '/search XXXX' 
- Will display a list of members who own a game for example: '/search dark souls' will return User1, User2, User3, etc
- Needs to support fuzzy search. Refer to link below
    - https://stackoverflow.com/questions/38421664/fuzzy-searching-with-mongodb
- Search will be done as part of an aggregation pipeline to link Games collection to Members collection in db.

**Comment by xtr3m3nerd** [comment]
fixed in commit 9d779e36ce5399d2e664202a0302490be1578cfa
