### ISSUE TITLE
We should make a superbot so we dont run into bot number restrictions. 

### ISSUE THREAD

**Issue by xtr3m3nerd** [PhilipBeckwith/Discord-Bots#4]
As briefly mentioned in the chat, and sounds like more so in the voice chat that I missed it sounds like we were talking about melding the functionality of the different bots we have into a larger super bot that can handle all of the different odd features that we are throwing at it. I figured I would create this issue to track our discussion on how we want to handle this idea. 

Here are my thoughts:

- Discord operates off of an event framework so we should be able to register multiple event handlers for each event (ie ready or message). This means that we shouldn't have to modify any of our existing behavior code for it to be able to work on one instance
- We only need one entry point to the app which remains the same so we have an index file that handles the login and token management for the bot. It would be responsible for passing the created client object to our modules for registering event handlers

With these points in mind I would imagine the index file to looks like 
```javascript
require('dotenv').config();
const Discord = require('discord'.js);
const client = new Discord.Client();

require('Budgett/index')(client);
require('MemeNarc/index')(client);
require('ScreechBot/index')(client);

const TOKEN = process.env.BOT_TOKEN;

client.login(TOKEN);
```
And each of the individual modules will just have their login information removed. 

If you guys are cool with this design I can open a branch for this and whip it up.

**Comment by xtr3m3nerd** [comment]
Revised change to preserve Budgett's integrity 

```javascript
require('dotenv').config();
const Discord = require('discord'.js);
const client = new Discord.Client();

require('Budgett/index'); // Budgett does not receive a client object because he spawns his own client on Wednesday my dudes
require('MemeNarc/index')(client);
require('ScreechBot/index')(client);
require('InsertFutureModuleHere/index')(client);

const TOKEN = process.env.BOT_TOKEN;

client.login(TOKEN);
```

**Comment by PhilipBeckwith** [comment]
Hmmm I'd like to see even more separation between multiple bots. So our main ("Global") index.js would still remain mostly as is, with some edits for setting up the environment. It will be responsible for booting all bots (Budgett/meggabot)(for now). Inside of our "megabot" folder would be the framework you're purposing here, where we have one client that's passed to a bunch of sub modules.
